name: Lint

on:
  workflow_call:

  push:
    branches: [main]

  pull_request:
    branches: [main]

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-commits:
    runs-on: ubuntu-22.04
    if: github.actor != 'dependabot[bot]'
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check commits
        uses: wagoid/commitlint-github-action@v4

  lint-markdown:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Lint markdown files
        uses: avto-dev/markdown-lint@v1.5.0
        with:
          args: "**/*.md"
          ignore: "CHANGELOG.md"

  lint-markdown-link:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Lint markdown links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: "yes"
          use-verbose-mode: "yes"
          base-branch: "main"
          config-file: ".mlc_config.json"

  lint-yaml:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Lint yaml files
        uses: ibiqlik/action-yamllint@v3.1.0

  lint-json:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint json files
        run: |
          sudo apt install -y jsonlint
          find ./ -type f -name "*.json" -exec sh -c '
            for file do
              if ! jsonlint-php -q "$file"; then
                echo "❌ $file"
                export FAILED=1
              else
                echo "✅ $file"
              fi
            done
            if [ "${FAILED}" = "1" ]; then
              exit 1
            fi
          ' sh {} +

  lint-dockerfile:
    runs-on: ubuntu-22.04
    if: github.actor != 'dependabot[bot]'
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Lint dockerfile (hadolint)
        uses: hadolint/hadolint-action@v2.1.0

  lint-go:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Find changed go files
        id: changed-go-files
        uses: tj-actions/changed-files@v34
        with:
          files: |
            **/*.go
            go.mod
            go.sum

      - name: Lint go code (golangci-lint)
        uses: golangci/golangci-lint-action@v3
        if: steps.changed-go-files.outputs.any_changed == 'true'
        with:
          version: v1.45

  lint-sql:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Lint SQL files
        uses: Bidaya0/sql-lint-in-action@v0.0.2
        with:
          path: "."

  lint-ts:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup node environment (for building)
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.0

      - name: Fetch dependencies
        run: |
          yarn

      - name: Lint typescript
        run: |
          yarn lint

  lint-kotlin:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Check gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Configure gradle.properties
        run: |
          cat <<EOF >> gradle.properties
          maven.credentials.username=${{ secrets.MAVEN_REPOSITORY_USERNAME }}
          maven.credentials.password=${{ secrets.MAVEN_REPOSITORY_PASSWORD }}
          EOF
      - name: Lint kotlin files
        uses: gradle/gradle-build-action@v2
        with:
          arguments: lint

  lint-poetry:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install Python Poetry
        uses: abatilo/actions-poetry@v2.1.6
        with:
          poetry-version: 1.1.11

      - name: Check poetry config is valid
        run: |
          poetry check

  lint-python:
    needs: lint-poetry
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install Python Poetry
        uses: abatilo/actions-poetry@v2.1.6
        with:
          poetry-version: 1.1.11

      - name: Install project dependencies
        run: |
          poetry install

      - name: Lint python code (flake8)
        run: |
          poetry run flake8 --count --show-source --statistics

      - name: Lint python code (
        uses: jpetrucciani/mypy-check@0.930
        with:
          path: "."

  lint-R:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup R environment
        uses: r-lib/actions/setup-r@v1
        with:
          use-public-rspm: true

      - name: Set R dependencies
        uses: r-lib/actions/setup-r-dependencies@v1
        with:
          extra-packages: lintr

      - name: Lint R code
        run: if(length(lintr::lint_dir()) >0) quit(status=1)
        shell: Rscript {0}

  lint-ontology:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup ruby environment
        uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.6"

      - run: |
          gem install rdf-turtle
      - name: Validate ontology file
        run: |
          rdf validate --validate src/okp4.ttl

  report-npm-new-dependencies:
    runs-on: ubuntu-22.04
    if: github.event_name == 'pull_request' && github.actor != 'dependabot[bot]'
    steps:
      - name: Check for new NPM dependencies
        uses: hiwelo/new-dependencies-action@1.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  lint-branch-name:
    runs-on: ubuntu-22.04
    if: github.actor != 'dependabot[bot]' && github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'reopened')
    steps:
      - name: Check branch name conventions
        uses: AlbertHernandez/branch-name-action@v1.0.2
        with:
          branch_pattern: "feat|fix|build|ci|docs|style|refactor|perf|test|chore"
          comment_for_invalid_branch_name: |
            🙋‍ Oops! This branch name does not follow the naming convention.
            <hr>
            Please, see the following branch naming convention:
            Branch naming convention | Purpose
            ------------------------ | -------
            `feat/**`                | A new feature
            `fix/**`                 | A bug fix
            `build/**`               | Changes that affect the build system (npm, mavem, poetry)
            `ci/**`                  | Changes to the CI configuration
            `docs/**`                | Documentation only changes
            `style/**`               | Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)
            `refactor/**`            | Code changes that neither fixe a bug nor adds a feature
            `perf/**`                | Code changes that improve performance
            `test/**`                | When adding tests or correcting existing tests
            `chore/**`               | Other changes that don't modify source
          fail_if_invalid_branch_name: "true"
          ignore_branch_pattern: "main"
      - name: Close non-compliant branch
        if: ${{ failure() }}
        uses: codelytv/no-pull-requests@v1
        with:
          GITHUB_TOKEN: ${{ secrets.OKP4_TOKEN }}
          message: 🙅 Closing the PR because it does not respect naming conventions. Edit the branch name and submit a new PR.
    env:
      GITHUB_TOKEN: ${{ secrets.OKP4_TOKEN }}

  lint-graphql:
    runs-on: ubuntu-22.04
    if: github.actor != 'dependabot[bot]'
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install graphql-schema-linter
        run: |
          npm install -g graphql-schema-linter graphql

      - name: Lint graphql schema (graphql-schema-linter)
        run: |
          graphql-schema-linter

  check-graphqls:
    runs-on: ubuntu-22.04
    if: github.actor != 'dependabot[bot]'
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Check graphql schema changes
        uses: kamilkisiela/graphql-inspector@v3.3.0
        with:
          schema: "main:graph/schema.graphqls"
          fail-on-breaking: false

  lint-shell:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Lint shell scripts
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: "./shell"
          version: "v0.8.0"

  lint-cargo-toml:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Find changed rust files
        id: changed-rust-cargo
        uses: tj-actions/changed-files@v34
        with:
          files: |
            Cargo.toml

      - name: Setup rust
        if: steps.changed-rust-cargo.outputs.any_changed == 'true'
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          default: true
          override: true

      - name: Install cargo-toml-lint
        if: steps.changed-rust-cargo.outputs.any_changed == 'true'
        run: |
          cargo install --force cargo-toml-lint
      - name: Lint toml files
        if: steps.changed-rust-cargo.outputs.any_changed == 'true'
        run: |
          cargo-toml-lint Cargo.toml

  lint-rust:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Find changed rust files
        id: changed-rust-files
        uses: tj-actions/changed-files@v34
        with:
          files: |
            **/*.rs
            Cargo.lock
            Cargo.toml

      - name: Setup rust
        if: steps.changed-rust-files.outputs.any_changed == 'true'
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          default: true
          override: true

      - name: Install cargo make
        if: steps.changed-rust-files.outputs.any_changed == 'true'
        uses: davidB/rust-cargo-make@v1

      - name: Lint rust code
        if: steps.changed-rust-files.outputs.any_changed == 'true'
        run: |
          cargo make lint-rust

  lint-rust-format:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          default: true
          override: true

      - name: Install cargo make
        uses: davidB/rust-cargo-make@v1

      - name: Check rust format
        run: |
          cargo make lint-rust-format

  lint-toml:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Setup rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          default: true
          override: true

      - name: Install cargo make
        uses: davidB/rust-cargo-make@v1

      - name: Lint toml
        run: |
          cargo make lint-toml

  lint-graphviz:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Graphviz
        run: |
          sudo apt install --no-install-recommends -y graphviz=2.42.2-6

      - name: Lint dot files
        run: |
          find ./ -type f -name "*.dot" -exec sh -c '
              for file do
              if ! dot "$file" > /dev/null; then
                  echo "❌ $file"
                  export FAILED=1
              else
                  echo "✅ $file"
              fi
              done
              if [ "${FAILED}" = "1" ]; then
              exit 1
              fi
          ' sh {} +

  lint-image:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Lint image files
        run: |
          find "$FOLDER" -regextype posix-egrep -regex '.+\.(ico|jpg|jpeg|png|svg|webp)' -exec sh -c '
            for file do
              if ! identify "$file" >/dev/null; then
                echo "❌ $file"
                export FAILED=1
              else
                echo "✅ $file"
              fi
            done
            if [ "${FAILED}" = "1" ]; then
              exit 1
            fi
          ' sh {} +
        env:
          FOLDER: .
