name: Test

on:
  workflow_call:

  push:
    branches: [main]

  pull_request:
    branches: [main]

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-go:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup Go environment
        uses: actions/setup-go@v3.0.0
        with:
          go-version: "1.17.6"

      - name: Test go project
        run: |
          make test-go

  test-ts:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup node environment
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.0

      - name: Fetch dependencies
        run: |
          yarn
      - name: Test typescript
        run: |
          yarn coverage
      - name: Upload coverage
        uses: codecov/codecov-action@v3
        if: github.actor != 'dependabot[bot]'
        with:
          files: ./coverage/lcov.info
          verbose: true
